export type ETF = {
  ticker: string;
  name: string;
  category: string;
};

export const ETF_UNIVERSE: ETF[] = [
  { ticker: "SPY",  name: "S&P 500",                 category: "Broad US Equity" },
  { ticker: "QQQ",  name: "Nasdaq-100",               category: "Broad US Equity" },
  { ticker: "IWM",  name: "Russell 2000",             category: "Broad US Equity" },
  { ticker: "IJH",  name: "S&P Mid-Cap 400",          category: "Broad US Equity" },
  { ticker: "MGK",  name: "Mega Cap Growth",          category: "Broad US Equity" },
  { ticker: "SPYG", name: "S&P 500 Growth",           category: "Broad US Equity" },
  { ticker: "SPYV", name: "S&P 500 Value",            category: "Broad US Equity" },
  { ticker: "SPMO", name: "S&P 500 Momentum",         category: "Broad US Equity" },
  { ticker: "SPHB", name: "S&P 500 High Beta",        category: "Broad US Equity" },
  { ticker: "SPLV", name: "S&P 500 Low Volatility",   category: "Broad US Equity" },
  { ticker: "SDY",  name: "S&P Dividend Aristocrats", category: "Broad US Equity" },
  { ticker: "XLK",  name: "Technology",               category: "US Sectors" },
  { ticker: "XLC",  name: "Communication Services",   category: "US Sectors" },
  { ticker: "XLY",  name: "Consumer Discretionary",   category: "US Sectors" },
  { ticker: "XLP",  name: "Consumer Staples",         category: "US Sectors" },
  { ticker: "XLI",  name: "Industrials",              category: "US Sectors" },
  { ticker: "XLU",  name: "Utilities",                category: "US Sectors" },
  { ticker: "XLE",  name: "Energy",                   category: "US Sectors" },
  { ticker: "XLV",  name: "Healthcare",               category: "US Sectors" },
  { ticker: "XLRE", name: "Real Estate",              category: "US Sectors" },
  { ticker: "XLF",  name: "Financials",               category: "US Sectors" },
  { ticker: "XLB",  name: "Materials",                category: "US Sectors" },
  { ticker: "XRT",  name: "Retail",                   category: "US Sectors" },
  { ticker: "AIQ",  name: "A.I.",                     category: "US Sectors" },
  { ticker: "CIBR", name: "Cyber Security",           category: "US Sectors" },
  { ticker: "GRID", name: "Power Infrastructure",     category: "US Sectors" },
  { ticker: "KIE",  name: "Insurance",                category: "US Sectors" },
  { ticker: "KRE",  name: "Regional Banks",           category: "US Sectors" },
  { ticker: "PAVE", name: "Infrastructure",           category: "US Sectors" },
  { ticker: "XHB",  name: "Homebuilders",             category: "US Sectors" },
  { ticker: "XHE",  name: "H/care Equipment",         category: "US Sectors" },
  { ticker: "XTN",  name: "Transportation",           category: "US Sectors" },
  { ticker: "SMH",  name: "Semiconductors",           category: "US Sectors" },
  { ticker: "VGK",  name: "Europe",                   category: "Intl - Dev Mrkt" },
  { ticker: "FEZ",  name: "Euro Stoxx 50",            category: "Intl - Dev Mrkt" },
  { ticker: "EWJ",  name: "Japan",                    category: "Intl - Dev Mrkt" },
  { ticker: "EWU",  name: "United Kingdom",           category: "Intl - Dev Mrkt" },
  { ticker: "EWC",  name: "Canada",                   category: "Intl - Dev Mrkt" },
  { ticker: "EWG",  name: "Germany",                  category: "Intl - Dev Mrkt" },
  { ticker: "EWQ",  name: "France",                   category: "Intl - Dev Mrkt" },
  { ticker: "EEM",  name: "Emerging Markets",         category: "Intl - Emer Mrkt" },
  { ticker: "EMXC", name: "EM ex-China",              category: "Intl - Emer Mrkt" },
  { ticker: "FXI",  name: "China Large Cap",          category: "Intl - Emer Mrkt" },
  { ticker: "KWEB", name: "China - Technology",       category: "Intl - Emer Mrkt" },
  { ticker: "CHIQ", name: "China - Consumer",         category: "Intl - Emer Mrkt" },
  { ticker: "INDA", name: "India",                    category: "Intl - Emer Mrkt" },
  { ticker: "SMIN", name: "India - Small Caps",       category: "Intl - Emer Mrkt" },
  { ticker: "EWW",  name: "Mexico",                   category: "Intl - Emer Mrkt" },
  { ticker: "VNM",  name: "Vietnam",                  category: "Intl - Emer Mrkt" },
  { ticker: "EZA",  name: "South Africa",             category: "Intl - Emer Mrkt" },
  { ticker: "AGG",  name: "US Aggregate Bond",        category: "Fixed Income" },
  { ticker: "IEF",  name: "7-10yr Treasury",          category: "Fixed Income" },
  { ticker: "IEI",  name: "3-7yr Treasury",           category: "Fixed Income" },
  { ticker: "TLT",  name: "20+yr Treasury",           category: "Fixed Income" },
  { ticker: "TIP",  name: "TIPS",                     category: "Fixed Income" },
  { ticker: "MUB",  name: "Municipal Bond",           category: "Fixed Income" },
  { ticker: "HYG",  name: "High Yield Corp Bond",     category: "Fixed Income" },
  { ticker: "LQD",  name: "Inv Grade Corp Bond",      category: "Fixed Income" },
  { ticker: "GSY",  name: "Ultra Short Bond",         category: "Fixed Income" },
  { ticker: "SPMB", name: "Mortgage-Backed",          category: "Fixed Income" },
  { ticker: "JNK",  name: "Junk Bonds",               category: "Fixed Income" },
  { ticker: "GLD",  name: "Gold",                     category: "Commodities & Alt" },
  { ticker: "SLV",  name: "Silver",                   category: "Commodities & Alt" },
  { ticker: "DBC",  name: "Commodities Index",        category: "Commodities & Alt" },
  { ticker: "DBA",  name: "Agriculture Fund",         category: "Commodities & Alt" },
  { ticker: "USO",  name: "Oil",                      category: "Commodities & Alt" },
  { ticker: "UUP",  name: "US Dollar",                category: "Commodities & Alt" },
  { ticker: "FXE",  name: "Euro",                     category: "Commodities & Alt" },
  { ticker: "FXY",  name: "Yen",                      category: "Commodities & Alt" },
  { ticker: "IBIT", name: "Bitcoin",                  category: "Commodities & Alt" },
];

export const ETFS: ETF[] = ETF_UNIVERSE.filter(
  (etf, idx, arr) => arr.findIndex(e => e.ticker === etf.ticker) === idx
);

export const CATEGORIES = [...new Set(ETFS.map(e => e.category))];
